name: octal_clock
description: A dart library to manage converting from standard times to octal time
version: 2.0.0
homepage: https://github.com/flutter-institute/lib_octal_clock.dart
repository: https://github.com/flutter-institute/lib_octal_clock.dart
issue_tracker: https://github.com/flutter-institute/lib_octal_clock.dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.1
