name: octal_clock
description: A dart library to manage converting from standard times to octal time
version: 1.0.0
homepage: https://github.com/killermonk/lib_octal_clock.dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.1
